# Generated by Django 2.0.5 on 2019-07-04 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180513_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='ending_time',
            field=models.DateField(default=datetime.datetime(2019, 8, 3, 15, 11, 26, 482805), verbose_name='应还时间'),
        ),
    ]
